events {}

http {
  upstream backend {
    server backend:4000;
  }

  upstream admin_web {
    server admin-web:3000;
  }

  server {
    listen 80;
    server_name api.roadguard.app;

    location / {
      proxy_pass http://backend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name admin.roadguard.app;

    location / {
      proxy_pass http://admin_web;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
